# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-23 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Salutation',
        ),
        migrations.AlterField(
            model_name='contact',
            name='Title',
            field=models.CharField(choices=[(b'Mr', b'Mr'), (b'Mrs.', b'Mrs'), (b'Ms', b'Ms')], max_length=9),
        ),
    ]
